/**
 * 共享文案表（2026-09-14 Phase 2b 自 `render/i18n.ts` 下沉）。
 *
 * STR 按 REPORT_LOCALE 在**模块加载期**定格选择（保留原语义——注入须先于本模块加载，
 * 见 setReportLocale 调用方约定）。单一真源：渲染层与组装层共用，避免各存一份。
 */
import { REPORT_LOCALE } from "./locale";

const TEXTS_ZH = {
  siteTitle: "每日简报",
  catTech: "技术动态",
  catFinance: "宏观政策",
  catPolitics: "时政观察",
  catTrading: "市场行情",
  catGdIpo: "广东地区IPO",
  catIpo: "IPO/新股",
  catCommunity: "社区讨论",
  subAiNews: "AI 媒体",
  subTrendingPapers: "热门论文",
  subXViral: "X 推文",
  subBlogWeekly: "博客周刊",
  subCnCommunity: "中文社区",
  subCnTech: "国内技术",
  subOverseasTech: "国外技术",
  subOverseasCommunity: "海外社区",
  subFinanceNews: "国际财经",
  subFinanceCn: "国内财经",
  subFinanceCommunity: "社区讨论",
  subWorld: "国际要闻",
  bandOfficial: "官方 / 政府一手来源",
  bandMedia: "媒体 / 智库解读",
  subOverseasNews: "海外科技",
  subOverseas: "海外",
  emptySource: "该源今日无内容。",
  emptyCategory: "该分类今日无内容。",
  emptyGroup: "该组今日无数据。",
  timeToday: "当天",
  timePast7: "过去7天",
  footer: "内容均来自原媒体，本站仅作摘要整理与回链。",
  summaryLabelNews: "AI分析",
  summaryLabelIntro: "AI分析",
  tradingMarketOverview: "市场总览",
  tradingTodayFocus: "今日关注",
  tradingAllAssets: "全部资产",
  tradingRiskCaveat: "风险提示",
  // 2026-09-14 移除 5 条加密 widget 死键（widgetCryptoFearGreed / widgetCryptoCap /
  // widgetBtcDom / widgetVolume24h / widgetActiveCoins）—— 加密资产零容忍（2026-09-12
  // 用户拍板，永久），且这 5 条在本仓无任何引用。静态断言见 tests/compliance-crypto.test.ts。
  ticker5d: "5 日",
  tickerVs52wHigh: "距 52w 高",
  tickerTrend: "趋势",
  tickerMacd: "MACD / 信号",
  signalToday: "今天",
  signalDaysAgoSuffix: "天前",
  trendBullish: "多头",
  trendBearish: "空头",
  trendNeutral: "中性",
  mdTodayOverview: "今日总览",
  mdEditorNote: "编辑短评",
  mdTodayKeywords: "今日关键词",
  mdImportance: "重要度",
  archiveLink: "← 历史归档",
  execInsightsShow: "条商机洞察",
  execInsightsHide: "收起商机洞察",
};

const TEXTS_EN: typeof TEXTS_ZH = {
  siteTitle: "Daily Brief",
  catTech: "Tech",
  catFinance: "Finance",
  catPolitics: "World",
  catTrading: "Markets",
  catGdIpo: "Guangdong IPO",
  catIpo: "IPO / New Listings",
  catCommunity: "Community",
  subAiNews: "AI Media",
  subTrendingPapers: "Trending Papers",
  subXViral: "X Viral",
  subBlogWeekly: "Blog Weekly",
  subCnCommunity: "Chinese Community",
  subCnTech: "Chinese Tech",
  subOverseasTech: "Overseas Tech",
  subOverseasCommunity: "Overseas Community",
  subFinanceNews: "Finance News",
  subFinanceCn: "Finance China",
  subFinanceCommunity: "Community",
  subWorld: "World News",
  bandOfficial: "Official / Government sources",
  bandMedia: "Media / Think-tank",
  subOverseasNews: "Overseas Tech",
  subOverseas: "Overseas",
  emptySource: "No content from this source today.",
  emptyCategory: "No content in this category today.",
  emptyGroup: "No data for this group today.",
  timeToday: "Today",
  timePast7: "Past 7d",
  footer:
    "Content sourced from original publishers; this site provides summary and backlinks only.",
  summaryLabelNews: "Summary",
  summaryLabelIntro: "Summary",
  tradingMarketOverview: "Market Overview",
  tradingTodayFocus: "Today's Focus",
  tradingAllAssets: "All Assets",
  tradingRiskCaveat: "Risk Disclaimer",
  ticker5d: "5d",
  tickerVs52wHigh: "vs 52w High",
  tickerTrend: "Trend",
  tickerMacd: "MACD / Signal",
  signalToday: "today",
  signalDaysAgoSuffix: "d ago",
  trendBullish: "Bullish",
  trendBearish: "Bearish",
  trendNeutral: "Neutral",
  mdTodayOverview: "Today's Overview",
  mdEditorNote: "Editor's Note",
  mdTodayKeywords: "Keywords",
  mdImportance: "Importance",
  archiveLink: "← Archive",
  execInsightsShow: "business insights",
  execInsightsHide: "Hide insights",
};

const STR = REPORT_LOCALE === "en" ? TEXTS_EN : TEXTS_ZH;

export { STR, TEXTS_ZH, TEXTS_EN };
